#!/bin/sh
set -euo pipefail

setUp() {
    export BUILDPACK_PATH=/tmp/common_spec
    mkdir -p $BUILDPACK_PATH
    touch $BUILDPACK_PATH/VERSION
    rm -rf $BUILDPACK_PATH/dependencies
}

tearDown() {
    unset BUILDPACK_PATH
}

testEchoContentOfVersion() {
    rm -f /tmp/echo_first_arg

    cat() {
      echo $1 >> /tmp/echo_first_arg
      echo '1.2.3'
    }

    OUTPUT=$(source $BIN/common)

    unset -f cat

    assertEquals '-------> Buildpack version 1.2.3' "$OUTPUT"
    assertEquals "${BUILDPACK_PATH}/VERSION" `cat /tmp/echo_first_arg`
}

# ==================================== Utilities ====================================

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BIN=$BASE/../lib
source $BASE/../vendor/shunit2
